### ISSUE TITLE
Autodelete head branches

### ISSUE THREAD

**Issue by zbynekwinkler** [ryanhiebert/probot-chain#6]
We have "Automatically delete head branches" set which deletes the branch when the PR is merged. But it can delete the branch only when there is no dependent PR. When the chain bot updates the base branch of the dependent PR, the original branch is no longer needed. Could chain bot delete this branch for us?

**Comment by ryanhiebert** [comment]
That sounds like a great idea, if we can do it without additional settings. I didn't realize that the setting wouldn't delete the branch if there are dependent PRs, and I'm really happy about that. If we can read the setting to determine whether or not to delete the branch, I'm all for adding in that deleting behavior to this app. I'm not sure when I'll get to it, but a PR would be welcome!

**Comment by ryanhiebert** [comment]
Welp, I made an attempt, but it's not working. I'll have to look at another time.

**Comment by zbynekwinkler** [comment]
I don't know what has changed but now the branch has been deleted after merging the PR even with dependent PR/branch existing. As far as I am concerned, its working! :+1:

**Comment by ryanhiebert** [comment]
Can you tell if the branch was deleted by this app?

**Comment by zbynekwinkler** [comment]
The github UI says that I have deleted the branch. On the dependent PR it says "Base automatically changed...". So... I don't know. It used to say that chainbot changed the base branch. Is there anything specific I should check?

**Comment by ryanhiebert** [comment]
Well, I expect that the dependent PR still says that chain bot changed the base branch. I'm wondering if it is hooked up correctly, or if it's deleting it after the hooks run or something.

**Comment by ryanhiebert** [comment]
OK, so it turns out that this whole app is basically unneeded. At least, I won't need it, given what I've found, and I have a hard time imagining a real use-case where someone _would_ need it.

GitHub will automatically change the base of pull requests that currently
have their head set to the branch being deleted if the deleting is done
automatically on merge or via the button on the pull request.

So if you merge a pull request, and then you click the "Delete branch" button:

![Delete branch button](https://raw.githubusercontent.com/ryanhiebert/probot-chain/master/obsolete-proof/delete-branch.png)

Then you'll see this on all the dependent pull requests:

![Base automatically changed activity](https://raw.githubusercontent.com/ryanhiebert/probot-chain/master/obsolete-proof/base-changed.png)

And this also works if you have GitHub delete branches automatically on merge:

![Automatically delete head branches checkbox in settings](https://raw.githubusercontent.com/ryanhiebert/probot-chain/master/obsolete-proof/auto-delete-on-merge.png)

So you probably don't need this. If you think you actually do need this, please let me know.

**One particular case that might catch you up** is that if you delete the branch via the **git cli**, it will NOT change the base branch of dependent pull requests, it will just close the issues. I expect that for most cases, though, having it delete head branches automatically, potentially combined with branch protection rules, will be the best way to deal with those cases.
